repositories:
- name: flux
  url: https://fluxcd.github.io/flux

releases:
- name: flux
  chart: fluxcd/flux
  # namespace: flux
  values:
  - git:
      url: {{ exec "sh" (list "-c" "config --get remote.origin.url | sed 's/\\.git$//'") }}
